# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!
  GO_PKG: github.com/lost-melody/yuman
  VERSION: 0.1.0
  GIT_COMMIT:
    sh: git rev-parse --short HEAD || echo unknown
  LOCALES_DIR: tr/locales
  LANG: zh-CN

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    desc: Build yuman
    cmds:
      - >-
        go build -ldflags
        "-X {{.GO_PKG}}/cmd.Version={{.VERSION}}
        -X {{.GO_PKG}}/cmd.GitCommit={{.GIT_COMMIT}}"

  i18n_extract:
    desc: Extract strings from source code
    cmds:
      - goi18n extract -outdir {{.LOCALES_DIR}}

  i18n_translate:
    desc: Create draft of strings to be translated
    cmds:
      - "test -f {{.LOCALES_DIR}}/active.{{.LANG}}.toml || touch {{.LOCALES_DIR}}/active.{{.LANG}}.toml"
      - >-
        goi18n merge -outdir {{.LOCALES_DIR}}
        {{.LOCALES_DIR}}/active.en.toml
        {{.LOCALES_DIR}}/active.{{.LANG}}.toml

  i18n_apply:
    desc: Apply strings into language pack
    cmds:
      - "test -f {{.LOCALES_DIR}}/active.{{.LANG}}.toml || touch {{.LOCALES_DIR}}/active.{{.LANG}}.toml"
      - >-
        goi18n merge -outdir {{.LOCALES_DIR}}
        {{.LOCALES_DIR}}/active.en.toml
        {{.LOCALES_DIR}}/active.{{.LANG}}.toml
        {{.LOCALES_DIR}}/translate.{{.LANG}}.toml
      - rm {{.LOCALES_DIR}}/translate.{{.LANG}}.toml
